### ISSUE TITLE
About open source license

### ISSUE THREAD

**Issue by willworks** [M6Guys/M6Guys.github.io#1]
来个M6 LICENSE嘿嘿嘿

**Comment by MervynFang** [comment]
火钳刘明

**Comment by MervynFang** [comment]
@willworks jiaopi said he will deal with it this weekend
<img width="421" alt="screen shot 2016-08-25 at 16 05 19" src="https://cloud.githubusercontent.com/assets/8202702/17961359/bf39b706-6add-11e6-818e-e2ed44ab59f7.png">

**Comment by PupateYf** [comment]
I just rejoice watching you zhuangbility in silence  : )

**Comment by holdenwen** [comment]
I'm just looking at you zhuangbility gays here : )

**Comment by sicatl** [comment]
The license has been existed, and I added the holders in it.

**Comment by PupateYf** [comment]
I'm greatly convinced that you zhuang a big b....
